<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5370" started-at="2019-05-02T20:44:34Z" finished-at="2019-05-02T20:44:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5370" started-at="2019-05-02T20:44:34Z" finished-at="2019-05-02T20:44:39Z">
      <class name="com.qa.test.TestTdApi">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="setUp" is-config="true" duration-ms="4" started-at="2019-05-02T13:44:34Z" finished-at="2019-05-02T13:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testCreateDatabase()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testCreateDatabase" duration-ms="1284" started-at="2019-05-02T13:44:34Z" finished-at="2019-05-02T13:44:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<200> but was:<409>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<409>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.qa.test.TestTdApi.testCreateDatabase(TestTdApi.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateDatabase -->
        <test-method status="FAIL" signature="testDeleteDatabase()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testDeleteDatabase" duration-ms="525" started-at="2019-05-02T13:44:35Z" finished-at="2019-05-02T13:44:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<200> but was:<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<404>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at com.qa.test.TestTdApi.testDeleteDatabase(TestTdApi.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteDatabase -->
        <test-method status="PASS" signature="testGetForAccountList()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testGetForAccountList" duration-ms="848" started-at="2019-05-02T13:44:36Z" finished-at="2019-05-02T13:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetForAccountList -->
        <test-method status="PASS" signature="testGetForDatabaseList()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testGetForDatabaseList" duration-ms="1349" started-at="2019-05-02T13:44:36Z" finished-at="2019-05-02T13:44:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetForDatabaseList -->
        <test-method status="PASS" signature="testGetTableInDatabase()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testGetTableInDatabase" duration-ms="571" started-at="2019-05-02T13:44:38Z" finished-at="2019-05-02T13:44:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetTableInDatabase -->
        <test-method status="PASS" signature="testToVerifyStatus()[pri:0, instance:com.qa.test.TestTdApi@20e2cbe0]" name="testToVerifyStatus" duration-ms="775" started-at="2019-05-02T13:44:38Z" finished-at="2019-05-02T13:44:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToVerifyStatus -->
      </class> <!-- com.qa.test.TestTdApi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
